export const GAME_STATUS = {
  INTRO: "INTRO",
  START: "START",
  PLAYING: "PLAYING",
  END: "END",
};

export const CARD_ACTIONS = {
  DEAL_PLAYER: "DEAL_PLAYER",
  DEAL_DEALER: "DEAL_DEALER",
  NEW_HAND: "NEW_HAND",
  TOGGLE_TURN: "TOGGLE_TURN",
  UPDATE_GAME_STATUS: "UPDATE_GAME_STATUS",
  SET_GAME_WINNER: "SET_GAME_WINNER",
};
